export default {
  program: "KYHS FE24",
  class: "WEBB24",
  yhPoints: 20,
  hours: 64,
  start: "v.34-v.37",
  startYear: 2025,
  startWeek: 34,
  endYear: 2025,
  endWeek: 37,
  plan: "/files/kursplan_webb24_cms.pdf",
  consultantDetails: {
    name: "Jonatan Vahlberg",
    email: "jonatan.vahlberg@nackademin.se",
    role: "Utbildningskonsult & Fullstackutvecklare",
    image: "/img/consultant.jpg",
  },
  tags: ["CMS", "Flipped-classroom (Semi-flipped)", "React", "Storyblok", "Next.js"],
  extraColumns: [
    {
      value: "time",
      label: "Tid",
      width: "40px",
    },
    {
      value: "mentorTime",
      label: "Mentortid",
      width: "120px",
    },
  ],
  schedule: [
    {
      week: 34,
      date: "18/8",
      content: "Vad är CMS?",
      time: "7h",
      mentorTime: "08:00-09:00",
    },
    {
      week: 34,
      date: "21/8",
      content: "Intro till Storyblok",
      time: "7h",
      mentorTime: "08:00-09:00",
    },
    {
      week: 35,
      date: "22/8",
      content: "Storyblok och Next.js",
      time: "7h",
      mentorTime: "08:00-09:00",
    },
    {
      week: 35,
      date: "25/8",
      content: "Storyblok och Next.js (Genomgång av gruppuppgiften)",
      time: "7h",
      mentorTime: "08:00-09:00",
    },
    {
      week: 36,
      date: "28/8",
      content: "Storyblok: Språkhantering + Arbete med uppgiften",
      time: "7h",
      mentorTime: "08:00-09:00, 14:00-16:00",
    },
    {
      week: 36,
      date: "29/8",
      content: "Storyblok: Avancerad användning",
      time: "7h",
      mentorTime: "08:00-09:00, 14:00-16:00",
    },
    {
      week: 37,
      date: "1/9",
      content: "Mentortid",
      time: "",
      mentorTime: "08:00-16:00",
    },
    {
      week: 37,
      date: "4/9",
      content: "Grupp presentationer",
      time: "7h",
      mentorTime: ""
    },
  ],
};
