export default {
  program: "KYHS FE24",
  class: "FE24",
  yhPoints: 20,
  hours: 56,
  start: "v.34-v.37",
  startYear: 2025,
  startWeek: 34,
  endYear: 2025,
  endWeek: 37,
  plan: "/files/KYH_FE24_Kursplan_Typescript.pdf",
  consultantDetails: {
    name: "Jonatan Vahlberg",
    email: "jonatan.vahlberg@nackademin.se",
    role: "Utbildningskonsult & Fullstackutvecklare",
    image: "/img/consultant.jpg",
  },
  tags: ["Typescipt", "Flipped-classroom"],
  extraColumns: [
    {
      value: "time",
      label: "Tid",
      width: "80px",
    },
  ],
  schedule: [
    {
      week: 34,
      date: "18/8",
      content: "Typescript: intro och genomgång (Distans)",
      time: "1h",
    },
    {
      week: 34,
      date: "21/8",
      content: "Handledning av lektion 1: Typescript (Distans)",
      time: "1h",
    },
    {
      week: 34,
      date: "22/8",
      content: "Lektion 2: Typescript koncept 6h (På plats)",
      time: "6h",
    },
    {
      week: 35,
      date: "25/8",
      content: "Handledning av lektion 3: Typescript innom React + Genomgång av Gruppuppgift (Distans)",
      time: "1h",
    },
    {
      week: 35,
      date: "28/8",
      content: "Handledning av gruppuppgiften (Distans)",
      time: "1h",
    },
    {
      week: 35,
      date: "29/8",
      content: "Lektion 4: Typescript innom React 2 (På plats)",
      time: "6h",
    },
    {
      week: 36,
      date: "1/9",
      content: "Handledning av lektion 4 (Distans)",
      time: "1h",
    },
    {
      week: 36,
      date: "4/9",
      content: "Grupp presentationer av grupparbete (Distans)",
      time: "1h",
    },
    {
      week: 36,
      date: "5/9",
      content: "Lektion 5: Generics, Guards och Assertions (På plats)",
      time: "6h",
    },
    {
      week: 37,
      date: "8/9",
      content: "Handledning av lektion 5 / Mentortid (Distans)",
      time: "1h",
    },
    {
      week: 37,
      date: "11/9",
      content: "Mentortid (Distans)",
      time: "1h",
    },
    {
      week: 37,
      date: "12/9",
      content: "Presentationer av individuella uppgiften (Distans i samanslagna grupper)",
      time: "6h",
    },
  ],
};
