import { cn } from '../../../../utils/cn'
import T from '../../Ui/TWTypography'

const FileName = ({
  file,
  isUploaded = false,
  isAutoGenerated = false,
  isGhost = false,
  error = false,
  isHovered = false,
  setIsHovered = () => {},
  onClick = () => {},
  asLink = false,
  className,
  ...nameProps
}) => {
  const nameClasses = cn('tw:!relative tw:!text-sm tw:!mb-0 tw:!line-clamp-1', {
    'tw:!cursor-pointer tw:hover:!filter tw:hover:!brightness-90': isUploaded && !error,
    'tw:!text-red-500 tw:!cursor-not-allowed': error,
    'tw:!text-gray-600': !error && !isGhost,
    'tw:!cursor-pointer tw:hover:!underline': !error && (isUploaded || isGhost || isAutoGenerated),
    'tw:!text-green-800': isUploaded && isGhost && !error,
    'tw:!filter tw:!brightness-75': isHovered && !error && (isUploaded || isAutoGenerated || isGhost),
    'tw:!text-blue-400 tw:!underline tw:hover:!text-blue-600 tw:!line-clamp-none': asLink && !error && isUploaded
  },
  className
)

  return (
    <T.Text title={file?.name} className={nameClasses} onClick={onClick} onMouseEnter={() => setIsHovered(true)} onMouseLeave={() => setIsHovered(false)} {...nameProps} >
      {file?.name}
    </T.Text>
  )
}

export default FileName
