import { cn } from "../../../../utils/cn";
import T from "../../Ui/TWTypography";

const FileName = ({
  file,
  isUploaded = false,
  isAutoGenerated = false,
  isGhost = false,
  error = false,
  isHovered = false,
  setIsHovered = () => {},
  onClick = () => {},
  asLink = false,
  className,
  ...nameProps
}) => {
  const nameClasses = cn(
    "relative text-sm mb-0 line-clamp-1",
    {
      "cursor-pointer hover:!filter hover:!brightness-90": isUploaded && !error,
      "text-red-500 cursor-not-allowed": error,
      "text-gray-600": !error && !isGhost,
      "cursor-pointer hover:!underline":
        !error && (isUploaded || isGhost || isAutoGenerated),
      "text-green-800": isUploaded && isGhost && !error,
      "filter brightness-75":
        isHovered && !error && (isUploaded || isAutoGenerated || isGhost),
      "text-blue-400 underline hover:!text-blue-600 line-clamp-none":
        asLink && !error && isUploaded,
    },
    className
  );

  return (
    <T.Text
      title={file?.name}
      className={nameClasses}
      onClick={onClick}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
      {...nameProps}
    >
      {file?.name}
    </T.Text>
  );
};

export default FileName;
