import File from '@/library/Form/Files/TWFile'
import { cn } from '@/utils/cn'
import { useFileDownloader } from '@/utils/hooks'
import React from 'react'

const ChatMessageAttachment = ({ attachment }) => {
  const { getToken } = useFileDownloader(attachment?.id, attachment?.download_url, {
    kindUrl: attachment?.download_url
  })
  
  return (
    <File
      file={attachment}
      isUploaded={true}
      isAutoGenerated={false}
      isDeletable={false}
      isEditable={false}
      iconSize='sm'
      asLink
      bg='gray'
      className='tw:!w-full'
      onClick={() => {
        getToken()
      }}
    />
  )
}

const ChatMessageAttachments = ({ direction = 'end', attachments, noPadding }) => {
  const attachmentWrapperClasses = cn('tw:!flex tw:!flex-wrap tw:!max-w-132.5 tw:!gap-2 tw:!items-center tw:!mt-2', {
    'tw:!justify-end tw:!pr-11.5': direction === 'end',
    'tw:!justify-start tw:!pl-11.5': direction === 'start',
    'tw:!pr-0 tw:!pl-0': noPadding
  })

  return attachments ? (
    <div className={attachmentWrapperClasses}>
      {attachments.map((attachment) => (
        <ChatMessageAttachment key={`${attachment.id}-${attachment.comment}`} attachment={attachment} />
      ))}
    </div>
  ) : null
}

export default ChatMessageAttachments
